portscan/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
# @Time  : 2018/4/9 16:01
# @Author: lxflxf
# @File  : urls.py
# @Ver   : 0.1
from django.urls import path
from . import views


app_name = 'portscan'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('add_scan/', views.AddScanView.as_view(), name='add_scan'),
    path('list_scan/', views.ScanListView.as_view(), name='list_scan'),
    path('detail_scan/<str:uuid>/', views.DetailListView.as_view(), name='detail_scan'),
    path('export/<str:uuid>/', views.ExportExcelView.as_view(), name='export_excel')
]

scanners/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('portscan.urls')),
]

portscan/models.py
from django.db import models
from datetime import datetime
import uuid


# Create your models here.
class ScanItems(models.Model):
    itemid = models.CharField(unique=True, max_length=100, default=uuid.uuid4, verbose_name='任务编号')
    scanname = models.CharField(max_length=50, verbose_name='扫描项目名', unique=True)
    scanIP = models.CharField(max_length=100, verbose_name='扫描IP段', unique=True)
    status = models.BooleanField(default=False, verbose_name='扫描状态')
    process = models.IntegerField(default=0, verbose_name='扫描进度')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '扫描项目'
        verbose_name_plural = verbose_name


class IPResult(models.Model):
    scannitem = models.ForeignKey(ScanItems, on_delete=models.CASCADE)
    ip = models.CharField(max_length=50, verbose_name='ip地址')

    class Meta:
        verbose_name = 'IP扫描结果'
        verbose_name_plural = verbose_name


class PortResult(models.Model):
    ip = models.ForeignKey(IPResult, on_delete=models.CASCADE)
    port = models.CharField(max_length=10, verbose_name='端口')
    service = models.CharField(max_length=500, verbose_name='服务')
    title = models.CharField(max_length=50, verbose_name='title')

    class Meta:
        verbose_name = '端口结果'
        verbose_name_plural = verbose_name

portscan/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
# @Time  : 2018/4/9 17:03
# @Author: lxflxf
# @File  : forms.py
# @Ver   : 0.1
from django import forms


class addItemForm(forms.Form):
    itemname = forms.CharField(max_length=100, required=True)
    ip = forms.CharField(max_length=100, required=True)


portscan/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, Http404
from django.views.generic import View, ListView, DetailView
from django.http import JsonResponse
from .forms import addItemForm
from .models import ScanItems, IPResult, PortResult
from scanclient.scantasks import start_scan

import ipaddress
import xlwt
from io import StringIO, BytesIO


# Create your views here.
class IndexView(View):
    """
    首页
    """
    def get(self, request):
        return render(request, 'dashboard.html')


class DashboardView(View):
    def get(self, request):
        return HttpResponse('123')


class ScanListView(ListView):
    template_name = 'scanners/list_scan.html'
    paginate_by = 10
    model = ScanItems
    context_object_name = 'scanitems'


class DetailListView(ListView):
    template_name = 'scanners/detail_scan.html'
    context_object_name = 'details'

    def get_queryset(self):
        self.scanitem = get_object_or_404(ScanItems, itemid=self.kwargs['uuid'])
        self.ipresult = IPResult.objects.get(scannitem=self.scanitem)
        return get_object_or_404(PortResult, ip=self.ipresult)


class AddScanView(View):
    def get(self, request):
        return render(request, 'scanners/add_scan.html')

    def post(self, request):
        add_form = addItemForm(request.POST)
        if add_form.is_valid():
            itemname = request.POST.get('itemname')
            ips = request.POST.get('ip')
            try:
                ipaddress.ip_network(ips, strict=False)
                scanitem = ScanItems(scanIP=ips, scanname=itemname)  #TODO：取多个重复值
                scanitem.save()
                start_scan.delay(scanitem.itemid)
                # return render(request, 'scanners/add_scan.html', {'msg': True})
                return JsonResponse({'msg': '提交成功', 'code': '1'})
            except Exception as e:
                print(e)
                return JsonResponse({'msg': '请输入正确的IP地址'})
        else:
            return JsonResponse({'msg': '请输入正确的数值'})


class ExportExcelView(View):
    """
    获取uuid参数，
    """
    def get(self, request, uuid):
        ws = self.export_excel(uuid)
        output = BytesIO()
        ws.save(output)
        output.seek(0)
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment;filename=result.xls'
        response.write(output.getvalue())
        return response

    def export_excel(self, uuid):
        scanitem = ScanItems.objects.get(itemid=uuid)
        ipresult = IPResult.objects.filter(scannitem=scanitem)
        if ipresult.exists():
            ws = xlwt.Workbook(encoding='utf-8')
            sheet = ws.add_sheet('port列表')
            sheet.write(0, 0, 'IP')
            sheet.write(0, 1, '端口')
            sheet.write(0, 2, '服务')
            sheet.write(0, 3, 'title')
            row = 1
            for ip in ipresult:
                portresult = PortResult.objects.filter(ip=ip)
                print(portresult)
                if portresult.exists():
                    for port in portresult:
                        sheet.write(row, 0, ip.ip)
                        sheet.write(row, 1, port.port)
                        sheet.write(row, 2, port.service)
                        sheet.write(row, 3, port.title)
                        row = row + 1
                else:
                    continue
            return ws

        else:
            raise Http404()

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Scanner v1.0</title>
	<meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <meta http-equiv="Cache-Control" content="no-siteapp" />

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
	<link rel="stylesheet" href="{% static 'css/xadmin.css' %}">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'lib/layui/layui.js' %}" charset="utf-8"></script>
    <script type="text/javascript" src="{% static 'js/xadmin.js' %}"></script>

</head>
<body>
    <!-- 顶部开始 -->
    <div class="container">
        <div class="logo"><a href="#">Scanner v1.0</a></div>
        <div class="left_open">
            <i title="展开左侧栏" class="iconfont">&#xe699;</i>
        </div>
        <!--<ul class="layui-nav left fast-add" lay-filter="">
          <li class="layui-nav-item">
            <a href="javascript:;">+新增</a>
            <dl class="layui-nav-child"> <!-- 二级菜单
              <dd><a onclick="x_admin_show('资讯','http://www.baidu.com')"><i class="iconfont">&#xe6a2;</i>资讯</a></dd>
              <dd><a onclick="x_admin_show('图片','http://www.baidu.com')"><i class="iconfont">&#xe6a8;</i>图片</a></dd>
               <dd><a onclick="x_admin_show('用户','http://www.baidu.com')"><i class="iconfont">&#xe6b8;</i>用户</a></dd>
            </dl>
          </li>
        </ul>-->
        <!-- <ul class="layui-nav right" lay-filter="">
          <li class="layui-nav-item">
            <a href="javascript:;">admin</a>
            <dl class="layui-nav-child"> <!-- 二级菜单
              <dd><a onclick="x_admin_show('个人信息','http://www.baidu.com')">个人信息</a></dd>
              <dd><a onclick="x_admin_show('切换帐号','http://www.baidu.com')">切换帐号</a></dd>
              <dd><a href="/static/login.html">退出</a></dd>
            </dl>
          </li>
          <li class="layui-nav-item to-index"><a href="/">前台首页</a></li>
        </ul>-->

    </div>
    <!-- 顶部结束 -->
    <!-- 中部开始 -->
     <!-- 左侧菜单开始 -->
    <div class="left-nav">
      <div id="side-nav">
        <ul id="nav">
            <li>
                <a href="javascript:;">
                    <i class="iconfont">&#xe6b8;</i>
                    <cite>扫描任务</cite>
                    <i class="iconfont nav_right">&#xe697;</i>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a _href="{% url 'portscan:add_scan' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>新建扫描</cite>

                        </a>
                    </li >
                    <li>
                        <a _href="{% url 'portscan:list_scan' %}">
                            <i class="iconfont">&#xe6a7;</i>
                            <cite>扫描列表</cite>

                        </a>
                    </li>
                </ul>
            </li>
        </ul>
      </div>
    </div>
    <!-- <div class="x-slide_left"></div> -->
    <!-- 左侧菜单结束 -->
    <!-- 右侧主体开始 -->
    <div class="page-content">
        <div class="layui-tab tab" lay-filter="xbs_tab" lay-allowclose="false">
          <ul class="layui-tab-title">
            <li>DashBoard</li>
          </ul>
          <div class="layui-tab-content">
            <div class="layui-tab-item layui-show">
                <iframe src='{% url 'portscan:dashboard' %}' frameborder="0" scrolling="yes" class="x-iframe"></iframe>
            </div>
          </div>
        </div>
    </div>
    <div class="page-content-bg"></div>
    <!-- 右侧主体结束 -->
    <!-- 中部结束 -->
    <!-- 底部开始 -->
    <div class="footer">
        <div class="copyright">Copyright ©2018 scanner v1.0 All Rights Reserved</div>
    </div>
    <!-- 底部结束 -->
</body>
</html>

templates/dashboard.html
{% extends "index.html" %}
{% block body %}
    dashboard
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Scanner v1.0</title>
  <link rel="stylesheet" href="{% static 'css/layui.css'%}">
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <div class="layui-logo">Scanners</div>
  </div>

  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <ul class="layui-nav layui-nav-tree"  lay-filter="test">
        <li class="layui-nav-item layui-nav-itemed">
          <a class="" href="javascript:;">扫描任务</a>
          <dl class="layui-nav-child">
            <dd><a href="{% url 'portscan:add_scan' %}">新建扫描</a></dd>
            <dd><a href="{% url 'portscan:list_scan' %}">扫描列表</a></dd>
          </dl>
        </li>
      </ul>
    </div>
  </div>

  <div class="layui-body">
  <div style="padding: 15px;">
      {% block body %}
        {% endblock %}
  </div>

  </div>

  <div class="layui-footer">
    <!-- 底部固定区域 -->
    © scanner v1.0
  </div>
</div>
<script src="{% static 'layui.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/scanners/add_scan.html
{% extends 'index.html' %}
{% load static %}
{% block js %}
<script type="text/javascript" src="{% static 'js/scanners/add.js' %}"></script>
{% endblock %}
{% block body %}
    <form class="layui-form">
        <div class="layui-form-item">
            <label class="layui-form-label">项目名称</label>
            <div class="layui-input-inline">
                <input name="itemname" type="text" lay-verify="required" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">扫描IP段</label>
            <div class="layui-input-inline">
                <input name="ip" type="text" lay-verify="required" autocomplete="off" class="layui-input">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit="" lay-filter="add">添加</button>
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
            </div>
        </div>
    {% csrf_token %}
    </form>
{% endblock %}

templates/scanners/detail_scan.html
{% extends "index.html" %}
{% block js %}
<script type="text/javascript" src="{% static 'js/scanners/detail.js'%}"></script>
{% endblock %}
{% block body %}
    <table class="layui-table">
        <thead>
          <tr>
            <th>IP</th>
            <th>Port</th>
            <th>title</th>
        </thead>
        <tbody>
        {% for detail in details %}
          <tr>
            <td>{{ detail.port }}</td>
            <td>{{ detail.service }}</td>
            <td>{{ detail.title }}</td>
        {% endfor %}
        </tbody>
      </table>
      <div class="page">
        <div>
          <a class="prev" href="">&lt;&lt;</a>
          <a class="num" href="">1</a>
          <span class="current">2</span>
          <a class="num" href="">3</a>
          <a class="num" href="">489</a>
          <a class="next" href="">&gt;&gt;</a>
        </div>
      </div>
{% endblock %}

<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8">
    <title>欢迎页面-X-admin2.0</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="/static/css/font.css">
    <link rel="stylesheet" href="/static/css/xadmin.css">
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="/static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
      <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="x-nav">
      <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right" href="javascript:location.replace(location.href);" title="刷新">
        <i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
      <table class="layui-table">
        <thead>
          <tr>
            <th>IP</th>
            <th>Port</th>
            <th>title</th>
        </thead>
        <tbody>
        {% for detail in details %}
          <tr>
            <td>{{ detail.port }}</td>
            <td>{{ detail.service }}</td>
            <td>{{ detail.title }}</td>
        {% endfor %}
        </tbody>
      </table>
      <div class="page">
        <div>
          <a class="prev" href="">&lt;&lt;</a>
          <a class="num" href="">1</a>
          <span class="current">2</span>
          <a class="num" href="">3</a>
          <a class="num" href="">489</a>
          <a class="next" href="">&gt;&gt;</a>
        </div>
      </div>
    </div>
  </body>

</html>

templates/scanners/list_scan.html
{% extends 'index.html' %}
{% load static %}
{% block js %}
<script type="text/javascript" src="{% static 'js/scanners/list.js' %}"></script>
{% endblock %}
{% block body %}
    <table lay-filter="listtable">
  <thead>
    <tr>
      <th lay-data="{type:'checkbox', fixed: 'left'}"></th>
      <th lay-data="{field:'uuid'}">项目uuid</th>
      <th lay-data="{field:'name', sort: true}">项目名称</th>
      <th lay-data="{field:'url'}">项目url</th>
      <th lay-data="{field:'addtime'}">添加时间</th>
      <th lay-data="{field:'status'}">状态</th>
      <th lay-data="{toolbar: '#barDemo'}">操作</th>
    </tr>
  </thead>
    <tbody>
        {% for item in scanitems %}
                <tr>
                    <td>
                        <div class="layui-unselect layui-form-checkbox" lay-skin="primary" data-id='2'><i class="layui-icon">&#xe605;</i></div>
                    </td>
                    <td>{{ item.itemid }}</td>
                    <td>{{ item.scanname }}</td>
                    <td>{{ item.scanIP }}</td>
                    <td>{{ item.add_time }}</td>
                    <td>{% if item.status %}<span class="layui-btn layui-btn-sm layui-btn-radius layui-btn-normal">完成</span>
                        {% else %}
                        <span class="layui-btn layui-btn-sm layui-btn-radius layui-btn-danger">正在扫描</span>
                        {% endif %}</td>
                    {% endfor %}
          </tr>
        </tbody>
    </tbody>
</table>
    {% if is_paginated %}
      <div class="page">
        <div>
            {% if page_obj.has_previous %}
          <a class="layui-btn layui-btn-primary" href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}
          <a class="layui-btn layui-btn-primary">第{{ page_obj.number }}页，共{{ page_obj.paginator.num_pages }}页</a>
        {% if page_obj.has_next %}
          <a class="layui-btn layui-btn-primary" href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        </div>
      </div>
    {% endif %}

<script type="text/html" id="barDemo">
  <a lay-event="detail" title="查看" href="javascript:;">
            <i class="layui-icon">&#xe63c;</i>
        </a>
        <a lay-event="download" title="下载" href="#">
            <i class="layui-icon">&#xe61e;</i>
        </a>
        <a lay-event="del" title="删除" href="javascript:;">
            <i class="layui-icon">&#xe640;</i>
        </a>
</script>
{% endblock %}